# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: capi-operator
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io/background
# spec:
#   project: default
#   source:
#     chart: cluster-api-operator
#     repoURL: https://kubernetes-sigs.github.io/cluster-api-operator
#     targetRevision: 0.14.0
#     helm:
#       releaseName: capi-operator
#       valuesObject:
#         core: "cluster-api:v1.9.0-beta.0"
#         infrastructure: "gcp;azure"
#         addon: helm
#         cert-manager:
#           enabled: "true"
#         configSecret:
#           name: credentials-secret
#           namespace: capi-operator-system
#       valueFiles:
#       - values.yaml
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: capi-operator-system
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - ServerSideApply=true
#     - CreateNamespace=true