apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: capi-operator/cluster-api-operator
    repoURL: https://kubernetes-sigs.github.io/cluster-api-operator
    helm:
      releaseName: capi-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
