# apiVersion: cluster.x-k8s.io/v1beta1
# kind: Cluster
# metadata:
#   name: capi-quickstart-azure
#   namespace: default
# spec:
#   clusterNetwork:
#     pods:
#       cidrBlocks:
#       - 192.168.0.0/16
#   controlPlaneRef:
#     apiVersion: controlplane.cluster.x-k8s.io/v1beta1
#     kind: KubeadmControlPlane
#     name: capi-quickstart-azure-control-plane
#   infrastructureRef:
#     apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
#     kind: AzureCluster
#     name: capi-quickstart-azure
# ---
# apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
# kind: AzureCluster
# metadata:
#   name: capi-quickstart-azure
#   namespace: default
# spec:
#   identityRef:
#     apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
#     kind: AzureClusterIdentity
#     name: cluster-identity
#   location: polandcentral
#   networkSpec:
#     subnets:
#     - name: control-plane-subnet
#       role: control-plane
#     - name: node-subnet
#       role: node
#     vnet:
#       name: capi-quickstart-azure-vnet
#   resourceGroup: capi-demo
#   subscriptionID: 19d20ac7-a18e-41a5-a74c-3a626574624d
# ---
# apiVersion: controlplane.cluster.x-k8s.io/v1beta1
# kind: KubeadmControlPlane
# metadata:
#   name: capi-quickstart-azure-control-plane
#   namespace: default
# spec:
#   kubeadmConfigSpec:
#     clusterConfiguration:
#       apiServer:
#         extraArgs:
#           cloud-provider: external
#         timeoutForControlPlane: 20m0s
#       controllerManager:
#         extraArgs:
#           allocate-node-cidrs: "false"
#           cloud-provider: external
#           cluster-name: capi-quickstart-azure
#       etcd:
#         local:
#           dataDir: /var/lib/etcddisk/etcd
#           extraArgs:
#             quota-backend-bytes: "8589934592"
#     diskSetup:
#       filesystems:
#       - device: /dev/disk/azure/scsi1/lun0
#         extraOpts:
#         - -E
#         - lazy_itable_init=1,lazy_journal_init=1
#         filesystem: ext4
#         label: etcd_disk
#       - device: ephemeral0.1
#         filesystem: ext4
#         label: ephemeral0
#         replaceFS: ntfs
#       partitions:
#       - device: /dev/disk/azure/scsi1/lun0
#         layout: true
#         overwrite: false
#         tableType: gpt
#     files:
#     - contentFrom:
#         secret:
#           key: control-plane-azure.json
#           name: capi-quickstart-azure-control-plane-azure-json
#       owner: root:root
#       path: /etc/kubernetes/azure.json
#       permissions: "0644"
#     initConfiguration:
#       nodeRegistration:
#         kubeletExtraArgs:
#           cloud-provider: external
#         name: '{{ ds.meta_data["local_hostname"] }}'
#     joinConfiguration:
#       nodeRegistration:
#         kubeletExtraArgs:
#           cloud-provider: external
#         name: '{{ ds.meta_data["local_hostname"] }}'
#     mounts:
#     - - LABEL=etcd_disk
#       - /var/lib/etcddisk
#     postKubeadmCommands: []
#     preKubeadmCommands: []
#   machineTemplate:
#     infrastructureRef:
#       apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
#       kind: AzureMachineTemplate
#       name: capi-quickstart-azure-control-plane
#   replicas: 3
#   version: v1.31.0
# ---
# apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
# kind: AzureMachineTemplate
# metadata:
#   name: capi-quickstart-azure-control-plane
#   namespace: default
# spec:
#   template:
#     spec:
#       dataDisks:
#       - diskSizeGB: 256
#         lun: 0
#         nameSuffix: etcddisk
#       identity: UserAssigned
#       osDisk:
#         diskSizeGB: 128
#         osType: Linux
#       sshPublicKey: ""
#       userAssignedIdentities:
#       - providerID: /subscriptions/19d20ac7-a18e-41a5-a74c-3a626574624d/resourceGroups/capz-ci/providers/Microsoft.ManagedIdentity/userAssignedIdentities/cloud-provider-user-identity
#       vmSize: Standard_D2s_v3
# ---
# apiVersion: cluster.x-k8s.io/v1beta1
# kind: MachineDeployment
# metadata:
#   name: capi-quickstart-azure-md-0
#   namespace: default
# spec:
#   clusterName: capi-quickstart-azure
#   replicas: 3
#   selector:
#     matchLabels: null
#   template:
#     spec:
#       bootstrap:
#         configRef:
#           apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
#           kind: KubeadmConfigTemplate
#           name: capi-quickstart-azure-md-0
#       clusterName: capi-quickstart-azure
#       infrastructureRef:
#         apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
#         kind: AzureMachineTemplate
#         name: capi-quickstart-azure-md-0
#       version: v1.31.0
# ---
# apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
# kind: AzureMachineTemplate
# metadata:
#   name: capi-quickstart-azure-md-0
#   namespace: default
# spec:
#   template:
#     spec:
#       osDisk:
#         diskSizeGB: 128
#         osType: Linux
#       sshPublicKey: ""
#       vmSize: Standard_D2s_v3
# ---
# apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
# kind: KubeadmConfigTemplate
# metadata:
#   name: capi-quickstart-azure-md-0
#   namespace: default
# spec:
#   template:
#     spec:
#       files:
#       - contentFrom:
#           secret:
#             key: worker-node-azure.json
#             name: capi-quickstart-azure-md-0-azure-json
#         owner: root:root
#         path: /etc/kubernetes/azure.json
#         permissions: "0644"
#       joinConfiguration:
#         nodeRegistration:
#           kubeletExtraArgs:
#             cloud-provider: external
#           name: '{{ ds.meta_data["local_hostname"] }}'
#       preKubeadmCommands: []
# ---
# apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
# kind: AzureClusterIdentity
# metadata:
#   labels:
#     clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
#   name: cluster-identity
#   namespace: default
# spec:
#   allowedNamespaces: {}
#   clientID: 63ffc492-30fd-4b9e-9836-8a415d096cef
#   tenantID: ae65f568-0ceb-42c2-9dda-731b9c16e6b4
#   type: WorkloadIdentity